/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/planned-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Planned Runs */
        get: operations["list_planned_runs_api_planned_runs_get"];
        put?: never;
        /** Create Planned Run */
        post: operations["create_planned_run_api_planned_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/planned-runs/{planned_run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Planned Run */
        get: operations["get_planned_run_api_planned_runs__planned_run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Activities */
        get: operations["list_activities_api_activities_get"];
        put?: never;
        /** Create Manual Activity */
        post: operations["create_manual_activity_api_activities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/imports/fit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Fit */
        post: operations["import_fit_api_activities_imports_fit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/{activity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Activity */
        get: operations["get_activity_api_activities__activity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/{activity_id}/corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Correction */
        post: operations["create_correction_api_activities__activity_id__corrections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/planned-runs/{planned_session_id}/outcomes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Session Outcome */
        post: operations["record_session_outcome_api_planned_runs__planned_session_id__outcomes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/planned-runs/{planned_session_id}/check-ins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Check In */
        post: operations["record_check_in_api_planned_runs__planned_session_id__check_ins_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/planned-runs/{planned_session_id}/linking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Link Evidence */
        get: operations["get_link_evidence_api_planned_runs__planned_session_id__linking_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/{activity_id}/linking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Activity Linking */
        get: operations["get_activity_linking_api_activities__activity_id__linking_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/{activity_id}/linking/candidates/{planned_session_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Match */
        post: operations["confirm_match_api_activities__activity_id__linking_candidates__planned_session_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/{activity_id}/linking/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change Current Link */
        put: operations["change_current_link_api_activities__activity_id__linking_link_put"];
        /** Create Direct Link */
        post: operations["create_direct_link_api_activities__activity_id__linking_link_post"];
        /** Remove Current Link */
        delete: operations["remove_current_link_api_activities__activity_id__linking_link_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/{activity_id}/linking/legacy-resolution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Legacy Links */
        post: operations["resolve_legacy_links_api_activities__activity_id__linking_legacy_resolution_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Stage One */
        post: operations["export_stage_one_api_export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityEntrySource
         * @enum {string}
         */
        ActivityEntrySource: "manual" | "fit_import";
        /** ActivityLinkRead */
        ActivityLinkRead: {
            link: components["schemas"]["LinkRead"];
            planned_run: components["schemas"]["PlannedRunRead"];
        };
        /**
         * ActivityLinkStatus
         * @enum {string}
         */
        ActivityLinkStatus: "unmatched" | "linked" | "legacy_unresolved";
        /** ActivityLinkingRead */
        ActivityLinkingRead: {
            activity: components["schemas"]["CompletedActivityRead"];
            link: components["schemas"]["ActivityLinkRead"] | null;
            /** Candidates */
            candidates: components["schemas"]["MatchCandidateRead"][];
            legacy_resolution: components["schemas"]["LegacyResolutionRead"] | null;
        };
        /**
         * ActivityModality
         * @enum {string}
         */
        ActivityModality: "running" | "cycling" | "strength" | "other";
        /** Body_import_fit_api_activities_imports_fit_post */
        Body_import_fit_api_activities_imports_fit_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** CheckInCreate */
        CheckInCreate: {
            /** Readiness */
            readiness?: number | null;
            /** Post Session Effort */
            post_session_effort?: number | null;
            /** Feel */
            feel?: number | null;
            /** Notes */
            notes?: string | null;
        };
        /** CheckInRead */
        CheckInRead: {
            /** Id */
            id: string;
            /** Planned Session Id */
            planned_session_id: string;
            /** Readiness */
            readiness: number | null;
            /** Post Session Effort */
            post_session_effort: number | null;
            /** Feel */
            feel: number | null;
            /** Notes */
            notes: string | null;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
        };
        /** CompletedActivityRead */
        CompletedActivityRead: {
            /** Id */
            id: string;
            modality: components["schemas"]["ActivityModality"];
            /**
             * Start Instant
             * Format: date-time
             */
            start_instant: string;
            /** Duration Seconds */
            duration_seconds: number;
            /** Distance Metres */
            distance_metres: number | null;
            /** Title */
            title: string | null;
            /** Notes */
            notes: string | null;
            entry_source: components["schemas"]["ActivityEntrySource"];
            /** Creation Provenance */
            creation_provenance: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** @default unmatched */
            link_status: components["schemas"]["ActivityLinkStatus"];
            import_provenance?: components["schemas"]["ImportProvenanceRead"] | null;
            /** Original Values */
            original_values: {
                [key: string]: string | number | null;
            };
            /** Corrections */
            corrections: components["schemas"]["CorrectionRead"][];
        };
        /** CorrectionCreate */
        CorrectionCreate: {
            /** Field Name */
            field_name: string;
            /** Replacement Value */
            replacement_value: string | number | null;
            /** Reason */
            reason: string;
        };
        /** CorrectionRead */
        CorrectionRead: {
            /** Id */
            id: string;
            /** Completed Activity Id */
            completed_activity_id: string;
            /** Field Name */
            field_name: string;
            /** Source Value */
            source_value: string | number | null;
            /** Replacement Value */
            replacement_value: string | number | null;
            /** Reason */
            reason: string;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
        };
        /** DirectLinkCreate */
        DirectLinkCreate: {
            /** Planned Session Id */
            planned_session_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportProvenanceRead */
        ImportProvenanceRead: {
            /** Adapter Type */
            adapter_type: string;
            /** Source Identity */
            source_identity: string;
            /** Importer Name */
            importer_name: string;
            /** Importer Version */
            importer_version: string;
            /**
             * Imported At
             * Format: date-time
             */
            imported_at: string;
            /** Raw File Identity */
            raw_file_identity: string;
            /** Checksum Sha256 */
            checksum_sha256: string;
            /** Original Normalized Values */
            original_normalized_values: {
                [key: string]: string | number | null;
            };
        };
        /** LegacyLinkRecordRead */
        LegacyLinkRecordRead: {
            /** Id */
            id: string;
            /** Planned Session Id */
            planned_session_id: string;
            planned_run: components["schemas"]["PlannedRunRead"];
            /** Linked Duration Seconds */
            linked_duration_seconds: number;
            /** Linked Distance Metres */
            linked_distance_metres: number | null;
            /** Confirmation Source */
            confirmation_source: string;
            /** Version */
            version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LegacyResolutionRead */
        LegacyResolutionRead: {
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Selected Planned Session Id */
            selected_planned_session_id: string | null;
            /** Resolved At */
            resolved_at: string | null;
            /** Records */
            records: components["schemas"]["LegacyLinkRecordRead"][];
        };
        /** LegacyResolutionRequest */
        LegacyResolutionRequest: {
            /** Planned Session Id */
            planned_session_id?: string | null;
        };
        /** LinkActivityEvidenceRead */
        LinkActivityEvidenceRead: {
            link: components["schemas"]["LinkRead"];
            activity: components["schemas"]["CompletedActivityRead"];
        };
        /** LinkChange */
        LinkChange: {
            /** Planned Session Id */
            planned_session_id: string;
            /** Expected Version */
            expected_version: number;
        };
        /** LinkEvidenceRead */
        LinkEvidenceRead: {
            planned_run: components["schemas"]["PlannedRunRead"];
            /** Links */
            links: components["schemas"]["LinkActivityEvidenceRead"][];
            /** Total Duration Seconds */
            total_duration_seconds: number;
            /** Total Distance Metres */
            total_distance_metres: number | null;
            /** Duration Difference Seconds */
            duration_difference_seconds: number | null;
            /** Distance Difference Metres */
            distance_difference_metres: number | null;
            session_outcome: components["schemas"]["SessionOutcomeRead"] | null;
            /** Session Outcome History */
            session_outcome_history: components["schemas"]["SessionOutcomeRead"][];
            check_in: components["schemas"]["CheckInRead"] | null;
            /** Check In History */
            check_in_history: components["schemas"]["CheckInRead"][];
        };
        /** LinkRead */
        LinkRead: {
            /** Id */
            id: string;
            /** Planned Session Id */
            planned_session_id: string;
            /** Completed Activity Id */
            completed_activity_id: string;
            /** Source */
            source: string;
            /** Algorithm Version */
            algorithm_version: string | null;
            /** Reasons */
            reasons: string[];
            /** Version */
            version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LinkRemove */
        LinkRemove: {
            /** Expected Version */
            expected_version: number;
        };
        /** ManualActivityCreate */
        ManualActivityCreate: {
            modality: components["schemas"]["ActivityModality"];
            /**
             * Start Instant
             * Format: date-time
             */
            start_instant: string;
            /** Duration Seconds */
            duration_seconds: number;
            /** Distance Metres */
            distance_metres?: number | null;
            /** Title */
            title?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** MatchCandidateRead */
        MatchCandidateRead: {
            planned_run: components["schemas"]["PlannedRunRead"];
            /** Algorithm Version */
            algorithm_version: string;
            /** Reasons */
            reasons: string[];
        };
        /** PlannedRunCreate */
        PlannedRunCreate: {
            /**
             * Scheduled Date
             * Format: date
             */
            scheduled_date: string;
            training_intent: components["schemas"]["TrainingIntent"];
            /** @default normal */
            priority: components["schemas"]["Priority"];
            /** Notes */
            notes?: string | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Distance Metres */
            distance_metres?: number | null;
        };
        /** PlannedRunRead */
        PlannedRunRead: {
            /** Id */
            id: string;
            /** Modality */
            modality: string;
            /**
             * Scheduled Date
             * Format: date
             */
            scheduled_date: string;
            training_intent: components["schemas"]["TrainingIntent"];
            priority: components["schemas"]["Priority"];
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            active_revision: components["schemas"]["PrescriptionRevisionRead"];
        };
        /** PrescriptionRevisionRead */
        PrescriptionRevisionRead: {
            /** Id */
            id: string;
            /** Revision Number */
            revision_number: number;
            /** Duration Seconds */
            duration_seconds: number | null;
            /** Distance Metres */
            distance_metres: number | null;
            /** Reason */
            reason: string;
            /** Provenance */
            provenance: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * Priority
         * @enum {string}
         */
        Priority: "low" | "normal" | "high";
        /** SessionOutcomeCreate */
        SessionOutcomeCreate: {
            /** Disposition */
            disposition: string;
            /** Reason */
            reason?: string | null;
        };
        /** SessionOutcomeRead */
        SessionOutcomeRead: {
            /** Id */
            id: string;
            /** Planned Session Id */
            planned_session_id: string;
            /** Disposition */
            disposition: string;
            /** Reason */
            reason: string | null;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
        };
        /**
         * TrainingIntent
         * @enum {string}
         */
        TrainingIntent: "recovery" | "aerobic_base" | "threshold" | "power" | "assessment";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_planned_runs_api_planned_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannedRunRead"][];
                };
            };
        };
    };
    create_planned_run_api_planned_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlannedRunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannedRunRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_planned_run_api_planned_runs__planned_run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planned_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannedRunRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_activities_api_activities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletedActivityRead"][];
                };
            };
        };
    };
    create_manual_activity_api_activities_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualActivityCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletedActivityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_fit_api_activities_imports_fit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_fit_api_activities_imports_fit_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletedActivityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_activity_api_activities__activity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletedActivityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_correction_api_activities__activity_id__corrections_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletedActivityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_session_outcome_api_planned_runs__planned_session_id__outcomes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planned_session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionOutcomeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOutcomeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_check_in_api_planned_runs__planned_session_id__check_ins_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planned_session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckInCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckInRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_link_evidence_api_planned_runs__planned_session_id__linking_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planned_session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkEvidenceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_activity_linking_api_activities__activity_id__linking_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityLinkingRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_match_api_activities__activity_id__linking_candidates__planned_session_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: string;
                planned_session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_current_link_api_activities__activity_id__linking_link_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_direct_link_api_activities__activity_id__linking_link_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DirectLinkCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_current_link_api_activities__activity_id__linking_link_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkRemove"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_legacy_links_api_activities__activity_id__linking_legacy_resolution_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LegacyResolutionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityLinkingRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_stage_one_api_export_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/zip": string;
                };
            };
        };
    };
}
