/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/planned-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Planned Runs */
        get: operations["list_planned_runs_api_planned_runs_get"];
        put?: never;
        /** Create Planned Run */
        post: operations["create_planned_run_api_planned_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/planned-runs/{planned_run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Planned Run */
        get: operations["get_planned_run_api_planned_runs__planned_run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Activities */
        get: operations["list_activities_api_activities_get"];
        put?: never;
        /** Create Manual Activity */
        post: operations["create_manual_activity_api_activities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/imports/fit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Fit */
        post: operations["import_fit_api_activities_imports_fit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/{activity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Activity */
        get: operations["get_activity_api_activities__activity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/planned-runs/{planned_session_id}/linking/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Suggestions */
        get: operations["get_suggestions_api_planned_runs__planned_session_id__linking_suggestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/planned-runs/{planned_session_id}/linking/suggestions/{activity_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Match Suggestion */
        post: operations["reject_match_suggestion_api_planned_runs__planned_session_id__linking_suggestions__activity_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/planned-runs/{planned_session_id}/linking/suggestions/{activity_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Match Suggestion */
        post: operations["confirm_match_suggestion_api_planned_runs__planned_session_id__linking_suggestions__activity_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/planned-runs/{planned_session_id}/linking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Link Evidence */
        get: operations["get_link_evidence_api_planned_runs__planned_session_id__linking_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/{activity_id}/linking/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Activity Suggestions */
        get: operations["get_activity_suggestions_api_activities__activity_id__linking_suggestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/{activity_id}/linking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Activity Linking */
        get: operations["get_activity_linking_api_activities__activity_id__linking_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/{activity_id}/linking/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Direct Link */
        post: operations["create_direct_link_api_activities__activity_id__linking_links_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/{activity_id}/linking/links/{link_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Adjust Link */
        put: operations["adjust_link_api_activities__activity_id__linking_links__link_id__put"];
        post?: never;
        /** Delete Link */
        delete: operations["delete_link_api_activities__activity_id__linking_links__link_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityEntrySource
         * @enum {string}
         */
        ActivityEntrySource: "manual" | "fit_import";
        /** ActivityLinkRead */
        ActivityLinkRead: {
            link: components["schemas"]["LinkRead"];
            planned_run: components["schemas"]["PlannedRunRead"];
        };
        /**
         * ActivityLinkStatus
         * @enum {string}
         */
        ActivityLinkStatus: "unmatched" | "partly_linked" | "linked";
        /** ActivityLinkingRead */
        ActivityLinkingRead: {
            activity: components["schemas"]["CompletedActivityRead"];
            /** Links */
            links: components["schemas"]["ActivityLinkRead"][];
            /** Remaining Duration Seconds */
            remaining_duration_seconds: number;
            /** Remaining Distance Metres */
            remaining_distance_metres: number | null;
        };
        /** ActivityMatchSuggestionRead */
        ActivityMatchSuggestionRead: {
            /** Activity Id */
            activity_id: string;
            planned_run: components["schemas"]["PlannedRunRead"];
            /** Algorithm Version */
            algorithm_version: string;
            /** Reasons */
            reasons: string[];
            /** Proposed Duration Seconds */
            proposed_duration_seconds: number;
            /** Proposed Distance Metres */
            proposed_distance_metres: number | null;
        };
        /**
         * ActivityModality
         * @enum {string}
         */
        ActivityModality: "running" | "cycling" | "strength" | "other";
        /** Body_import_fit_api_activities_imports_fit_post */
        Body_import_fit_api_activities_imports_fit_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** CompletedActivityRead */
        CompletedActivityRead: {
            /** Id */
            id: string;
            modality: components["schemas"]["ActivityModality"];
            /**
             * Start Instant
             * Format: date-time
             */
            start_instant: string;
            /** Duration Seconds */
            duration_seconds: number;
            /** Distance Metres */
            distance_metres: number | null;
            /** Title */
            title: string | null;
            /** Notes */
            notes: string | null;
            entry_source: components["schemas"]["ActivityEntrySource"];
            /** Creation Provenance */
            creation_provenance: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** @default unmatched */
            link_status: components["schemas"]["ActivityLinkStatus"];
            import_provenance?: components["schemas"]["ImportProvenanceRead"] | null;
        };
        /** DirectLinkCreate */
        DirectLinkCreate: {
            /** Planned Session Id */
            planned_session_id: string;
            /** Linked Duration Seconds */
            linked_duration_seconds: number;
            /** Linked Distance Metres */
            linked_distance_metres?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportProvenanceRead */
        ImportProvenanceRead: {
            /** Adapter Type */
            adapter_type: string;
            /** Source Identity */
            source_identity: string;
            /** Importer Name */
            importer_name: string;
            /** Importer Version */
            importer_version: string;
            /**
             * Imported At
             * Format: date-time
             */
            imported_at: string;
            /** Raw File Identity */
            raw_file_identity: string;
            /** Checksum Sha256 */
            checksum_sha256: string;
            /** Original Normalized Values */
            original_normalized_values: {
                [key: string]: string | number | null;
            };
        };
        /** LinkActivityEvidenceRead */
        LinkActivityEvidenceRead: {
            link: components["schemas"]["LinkRead"];
            activity: components["schemas"]["CompletedActivityRead"];
            /** Unmatched Duration Seconds */
            unmatched_duration_seconds: number;
            /** Unmatched Distance Metres */
            unmatched_distance_metres: number | null;
        };
        /** LinkEvidenceRead */
        LinkEvidenceRead: {
            planned_run: components["schemas"]["PlannedRunRead"];
            /** Links */
            links: components["schemas"]["LinkActivityEvidenceRead"][];
            /** Total Linked Duration Seconds */
            total_linked_duration_seconds: number;
            /** Total Linked Distance Metres */
            total_linked_distance_metres: number | null;
            /** Duration Difference Seconds */
            duration_difference_seconds: number | null;
            /** Distance Difference Metres */
            distance_difference_metres: number | null;
            /** Session Outcome */
            session_outcome?: null;
        };
        /** LinkRead */
        LinkRead: {
            /** Id */
            id: string;
            /** Planned Session Id */
            planned_session_id: string;
            /** Completed Activity Id */
            completed_activity_id: string;
            /** Linked Duration Seconds */
            linked_duration_seconds: number;
            /** Linked Distance Metres */
            linked_distance_metres: number | null;
            /** Confirmation Source */
            confirmation_source: string;
            /** Version */
            version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LinkUpdate */
        LinkUpdate: {
            /** Linked Duration Seconds */
            linked_duration_seconds: number;
            /** Linked Distance Metres */
            linked_distance_metres?: number | null;
            /** Expected Version */
            expected_version: number;
        };
        /** ManualActivityCreate */
        ManualActivityCreate: {
            modality: components["schemas"]["ActivityModality"];
            /**
             * Start Instant
             * Format: date-time
             */
            start_instant: string;
            /** Duration Seconds */
            duration_seconds: number;
            /** Distance Metres */
            distance_metres?: number | null;
            /** Title */
            title?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** MatchSuggestionRead */
        MatchSuggestionRead: {
            /** Planned Session Id */
            planned_session_id: string;
            /** Prescription Revision Id */
            prescription_revision_id: string;
            activity: components["schemas"]["CompletedActivityRead"];
            /** Algorithm Version */
            algorithm_version: string;
            /** Reasons */
            reasons: string[];
            /** Proposed Duration Seconds */
            proposed_duration_seconds: number;
            /** Proposed Distance Metres */
            proposed_distance_metres: number | null;
        };
        /** PlannedRunCreate */
        PlannedRunCreate: {
            /**
             * Scheduled Date
             * Format: date
             */
            scheduled_date: string;
            training_intent: components["schemas"]["TrainingIntent"];
            /** @default normal */
            priority: components["schemas"]["Priority"];
            /** Notes */
            notes?: string | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Distance Metres */
            distance_metres?: number | null;
        };
        /** PlannedRunRead */
        PlannedRunRead: {
            /** Id */
            id: string;
            /** Modality */
            modality: string;
            /**
             * Scheduled Date
             * Format: date
             */
            scheduled_date: string;
            training_intent: components["schemas"]["TrainingIntent"];
            priority: components["schemas"]["Priority"];
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            active_revision: components["schemas"]["PrescriptionRevisionRead"];
        };
        /** PrescriptionRevisionRead */
        PrescriptionRevisionRead: {
            /** Id */
            id: string;
            /** Revision Number */
            revision_number: number;
            /** Duration Seconds */
            duration_seconds: number | null;
            /** Distance Metres */
            distance_metres: number | null;
            /** Reason */
            reason: string;
            /** Provenance */
            provenance: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * Priority
         * @enum {string}
         */
        Priority: "low" | "normal" | "high";
        /** SuggestionConfirm */
        SuggestionConfirm: {
            /** Linked Duration Seconds */
            linked_duration_seconds?: number | null;
            /** Linked Distance Metres */
            linked_distance_metres?: number | null;
        };
        /** SuggestionDecisionRead */
        SuggestionDecisionRead: {
            /** Decision */
            decision: string;
        };
        /**
         * TrainingIntent
         * @enum {string}
         */
        TrainingIntent: "recovery" | "aerobic_base" | "threshold" | "power" | "assessment";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_planned_runs_api_planned_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannedRunRead"][];
                };
            };
        };
    };
    create_planned_run_api_planned_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlannedRunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannedRunRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_planned_run_api_planned_runs__planned_run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planned_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannedRunRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_activities_api_activities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletedActivityRead"][];
                };
            };
        };
    };
    create_manual_activity_api_activities_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualActivityCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletedActivityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_fit_api_activities_imports_fit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_fit_api_activities_imports_fit_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletedActivityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_activity_api_activities__activity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletedActivityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_suggestions_api_planned_runs__planned_session_id__linking_suggestions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planned_session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchSuggestionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_match_suggestion_api_planned_runs__planned_session_id__linking_suggestions__activity_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planned_session_id: string;
                activity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionDecisionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_match_suggestion_api_planned_runs__planned_session_id__linking_suggestions__activity_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planned_session_id: string;
                activity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuggestionConfirm"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_link_evidence_api_planned_runs__planned_session_id__linking_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planned_session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkEvidenceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_activity_suggestions_api_activities__activity_id__linking_suggestions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityMatchSuggestionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_activity_linking_api_activities__activity_id__linking_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityLinkingRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_direct_link_api_activities__activity_id__linking_links_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DirectLinkCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    adjust_link_api_activities__activity_id__linking_links__link_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: string;
                link_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_link_api_activities__activity_id__linking_links__link_id__delete: {
        parameters: {
            query: {
                expected_version: number;
            };
            header?: never;
            path: {
                activity_id: string;
                link_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
