/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/planned-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Planned Run */
        post: operations["create_planned_run_api_planned_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/planned-runs/{planned_run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Planned Run */
        get: operations["get_planned_run_api_planned_runs__planned_run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Activities */
        get: operations["list_activities_api_activities_get"];
        put?: never;
        /** Create Manual Activity */
        post: operations["create_manual_activity_api_activities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/imports/fit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Fit */
        post: operations["import_fit_api_activities_imports_fit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/{activity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Activity */
        get: operations["get_activity_api_activities__activity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityEntrySource
         * @enum {string}
         */
        ActivityEntrySource: "manual" | "fit_import";
        /**
         * ActivityModality
         * @enum {string}
         */
        ActivityModality: "running" | "cycling" | "strength" | "other";
        /** Body_import_fit_api_activities_imports_fit_post */
        Body_import_fit_api_activities_imports_fit_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** CompletedActivityRead */
        CompletedActivityRead: {
            /** Id */
            id: string;
            modality: components["schemas"]["ActivityModality"];
            /**
             * Start Instant
             * Format: date-time
             */
            start_instant: string;
            /** Duration Seconds */
            duration_seconds: number;
            /** Distance Metres */
            distance_metres: number | null;
            /** Title */
            title: string | null;
            /** Notes */
            notes: string | null;
            entry_source: components["schemas"]["ActivityEntrySource"];
            /** Creation Provenance */
            creation_provenance: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Reconciliation Status
             * @default unmatched
             */
            reconciliation_status: string;
            import_provenance?: components["schemas"]["ImportProvenanceRead"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportProvenanceRead */
        ImportProvenanceRead: {
            /** Adapter Type */
            adapter_type: string;
            /** Source Identity */
            source_identity: string;
            /** Importer Name */
            importer_name: string;
            /** Importer Version */
            importer_version: string;
            /**
             * Imported At
             * Format: date-time
             */
            imported_at: string;
            /** Raw File Identity */
            raw_file_identity: string;
            /** Checksum Sha256 */
            checksum_sha256: string;
            /** Original Normalized Values */
            original_normalized_values: {
                [key: string]: string | number | null;
            };
        };
        /** ManualActivityCreate */
        ManualActivityCreate: {
            modality: components["schemas"]["ActivityModality"];
            /**
             * Start Instant
             * Format: date-time
             */
            start_instant: string;
            /** Duration Seconds */
            duration_seconds: number;
            /** Distance Metres */
            distance_metres?: number | null;
            /** Title */
            title?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** PlannedRunCreate */
        PlannedRunCreate: {
            /**
             * Scheduled Date
             * Format: date
             */
            scheduled_date: string;
            training_intent: components["schemas"]["TrainingIntent"];
            /** @default normal */
            priority: components["schemas"]["Priority"];
            /** Notes */
            notes?: string | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Distance Metres */
            distance_metres?: number | null;
        };
        /** PlannedRunRead */
        PlannedRunRead: {
            /** Id */
            id: string;
            /** Modality */
            modality: string;
            /**
             * Scheduled Date
             * Format: date
             */
            scheduled_date: string;
            training_intent: components["schemas"]["TrainingIntent"];
            priority: components["schemas"]["Priority"];
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            active_revision: components["schemas"]["PrescriptionRevisionRead"];
        };
        /** PrescriptionRevisionRead */
        PrescriptionRevisionRead: {
            /** Id */
            id: string;
            /** Revision Number */
            revision_number: number;
            /** Duration Seconds */
            duration_seconds: number | null;
            /** Distance Metres */
            distance_metres: number | null;
            /** Reason */
            reason: string;
            /** Provenance */
            provenance: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * Priority
         * @enum {string}
         */
        Priority: "low" | "normal" | "high";
        /**
         * TrainingIntent
         * @enum {string}
         */
        TrainingIntent: "recovery" | "aerobic_base" | "threshold" | "power" | "assessment";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_planned_run_api_planned_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlannedRunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannedRunRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_planned_run_api_planned_runs__planned_run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planned_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlannedRunRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_activities_api_activities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletedActivityRead"][];
                };
            };
        };
    };
    create_manual_activity_api_activities_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualActivityCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletedActivityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_fit_api_activities_imports_fit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_fit_api_activities_imports_fit_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletedActivityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_activity_api_activities__activity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletedActivityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
